[MEETRAVEL-52] 버튼 컴포넌트 추가
meetravel-official/meetravel-front pull request #13
Opened 2024-08-02 07:30 UTC by lyn94

- 버튼 관련 이전 PR에서 hover 상태가 추가되었습니다.
- 임의적으로 조금 더 어둡게 처리되도록 수정했습니다.

2024-08-03 17:08 UTC, iioo3356 requested changes

2024-08-03 17:08 UTC, iioo3356 commented on .vscode/launch.json
요 vscode 설정 파일 꼭 필요하지 않으면 gitignore에 등록해두시는 건 어떨까용?

2024-08-03 17:08 UTC, iioo3356 commented on src/components/Button/Button.tsx
> +        default:
버튼 사이즈에 100%나 auto 를 문자열로 넣어주면 여기 스위치문에서 무조건 48픽셀로 바뀌지 않을까요?

2024-08-08 04:43 UTC, iioo3356 commented on src/components/Button/Button.tsx
> +        default:
확인했습니다! 감사합니당

2024-08-08 04:43 UTC, iioo3356 approved these changes
👍

2024-08-08 05:25 UTC, suyunup approved these changes
👍👍👍

2024-08-08 08:00 UTC, merged